timings:
  COAL_ORE: 300000
  DEEPSLATE_COAL_ORE: 300000
  COPPER_ORE: 600000
  DEEPSLATE_COPPER_ORE: 600000
  LAPIS_ORE: 900000
  DEEPSLATE_LAPIS_ORE: 900000
  REDSTONE_ORE: 900000
  DEEPSLATE_REDSTONE_ORE: 900000
  IRON_ORE: 1800000
  DEEPSLATE_IRON_ORE: 1800000
  GOLD_ORE: 1800000
  DEEPSLATE_GOLD_ORE: 1800000
  DIAMOND_ORE: 3600000
  DEEPSLATE_DIAMOND_ORE: 3600000
  EMERALD_ORE: 3600000
  DEEPSLATE_EMERALD_ORE: 3600000
  NETHER_QUARTZ_ORE: 300000
  NETHER_GOLD_ORE: 300000
  ANCIENT_DEBRIS: 7200000
sql:
  database: reore
  locationsTable: locations
locale: en
locales:
  ru:
    added: добавлен в список возобновляемых ресурсов
    already: уже
    block-with-coordinates: Блок с координатами
    cooldown: Ресурс восстановится через
    in-list: состоит в списке возобновляемых ресурсов
    in-world: в мире
    non: не
    not: не
    now: теперь
    reloaded: Конфигурационные данные перезагружены
    removed: удален из списка возобновлемых ресурсов
    renewable: возобновлемые
    resources-in-region: Ресурсы в регионе
    success: успешно
    syntax-error: Синтаксическая ошибка при выполнении команды
  en:
    added: added to replenishing nodes list
    already: is already
    block-with-coordinates: Block with coordinates
    cooldown: The node will replenish in
    in-list: in replenishing nodes list
    in-world: in the world
    non: non-
    not: is not
    now: are now
    reloaded: Config reloaded
    removed: removed from the replenishing nodes list
    renewable: renewable
    resources-in-region: Resources in selected WorldEdit region
    success: successfully
    syntax-error: Syntax error during command execution