timings:
  COAL_ORE: 300000
  DEEPSLATE_COAL_ORE: 300000
  COPPER_ORE: 600000
  DEEPSLATE_COPPER_ORE: 600000
  LAPIS_ORE: 900000
  DEEPSLATE_LAPIS_ORE: 900000
  REDSTONE_ORE: 900000
  DEEPSLATE_REDSTONE_ORE: 900000
  IRON_ORE: 1800000
  DEEPSLATE_IRON_ORE: 1800000
  GOLD_ORE: 1800000
  DEEPSLATE_GOLD_ORE: 1800000
  DIAMOND_ORE: 3600000
  DEEPSLATE_DIAMOND_ORE: 3600000
  EMERALD_ORE: 3600000
  DEEPSLATE_EMERALD_ORE: 3600000
  NETHER_QUARTZ_ORE: 300000
  NETHER_GOLD_ORE: 300000
  ANCIENT_DEBRIS: 7200000
sql:
  database: reore
  locationsTable: locations
locale: en
locales:
  ru:
    add-success: Ресурс успешно добавлен
    add-failure: Не получилось добавить ресурс
    remove-success: Ресурс успешно удален
    remove-failure: Не получилось удалить ресурс
    cooldown: Ресурс восстановится через 
  en:
    add-success: The node is added successfully
    add-failure: Failed to add the node
    remove-success: The node is removed successfully
    remove-failure: Failed to remove the node
    cooldown: The node will replenish in